import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.css";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "/public/assets/css/animate.min.css";
import "/public/assets/css/bootstrap.min.css";
import "/public/assets/css/fontawesome-all.min.css";
import "/public/assets/css/magnific-popup.css";
import "/public/assets/css/odometer.css";
import "/public/assets/css/animatedheadline.css";
import "/public/assets/css/default.css";
import "/public/assets/css/select2.min.css";
import "/public/assets/css/style.css";
import "/public/assets/css/responsive.css";
import { Toaster } from "react-hot-toast";
import { ThemeRegistry } from "@/theme/ThemeRegistry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeRegistry options={{ key: "mui" }}>
          {/* <Authentication /> */}
          {children}
          <Toaster />
        </ThemeRegistry>
      </body>
    </html>
  );
}
